name: tinycolormap

on:
  workflow_dispatch:
  push:
    paths:
      - tinycolormap/**
  pull_request:
    paths:
      - tinycolormap/**

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build conda package
      uses: prefix-dev/rattler-build-action@v0.2.0
      with:
        recipe-path: tinycolormap/recipe.yaml
        build-args: -c https://repo.prefix.dev/zicklag-forge -c conda-forge
    - run: echo ${{ github.ref }} / ${{ github.event_name }}
    - name: Upload Package
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: |
        for pkg in $(find output -type f \( -name "*.conda" -o -name "*.tar.bz2" \) ); do
          echo "Uploading ${pkg}"
          rattler-build upload prefix -c zicklag-forge "${pkg}"
        done
      env:
        PREFIX_API_KEY: ${{ secrets.PREFIX_API_KEY }}
